CREATE DATABASE AS_DB_CLINICA
go
USE AS_DB_CLINICA
GO

CREATE TABLE TIPOUSER(
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TIPO varchar(40) NOT NULL,
)
GO
CREATE TABLE USUARIOS(
ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY, 
USUARIO VARCHAR (50) NOT NULL, 
CONTRASENIA VARCHAR (50) NOT NULL,
IDTIPOUSER INT FOREIGN KEY REFERENCES TIPOUSER (ID) NOT NULL
)
GO 
CREATE TABLE ESTADOS (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
ESTADO VARCHAR (60) NOT NULL
)
GO 
CREATE TABLE ESPECIALIDADES (
ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY, 
ESPECIALIDAD VARCHAR (60) NOT NULL,
)
GO 
CREATE TABLE HORARIOS (
ID INT IDENTITY (1,1) PRIMARY KEY,
DIA VARCHAR (9) NOT NULL, 
HORARIOINICIO VARCHAR (5), 
HORARIOFIN VARCHAR(5)
)
GO 
CREATE TABLE USUARIOSDATOSPERSONALES (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
NOMBRE VARCHAR (60) NOT NULL, 
APELLIDO VARCHAR (60) NOT NULL, 
DNI VARCHAR (60) NULL, 
EMAIL VARCHAR (60) NULL,
SEXO VARCHAR (1) NOT NULL,
IDUSUARIO INT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
)

GO 
CREATE TABLE MEDICOS (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
ID_USUARIODATOPERSONAL INT FOREIGN KEY REFERENCES USUARIOSDATOSPERSONALES(ID)
)
GO 
CREATE TABLE PACIENTES (
ID INT PRIMARY KEY NOT NULL IDENTITY (1,1), 
FECHANACIMIENTO DATE NOT NULL, 
DIRECCION VARCHAR (60) NULL, 
CONTACTO VARCHAR (60) NULL,
ID_USUARIODATOPERSONAL INT FOREIGN KEY REFERENCES USUARIOSDATOSPERSONALES(ID)
)
GO 
CREATE TABLE TURNOS (
ID INT PRIMARY KEY NOT NULL IDENTITY (1,1), 
IDPACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTES (ID), 
IDMEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS (ID), 
IDESPECIALIDAD INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES (ID), 
FECHA DATE NOT NULL, 
HORARIO VARCHAR (5) NOT NULL,
IDESTADO INT NOT NULL FOREIGN KEY REFERENCES ESTADOS (ID)
)
GO 
CREATE TABLE MEDICOXESPECIALIDAD (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
IDMEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS(ID), 
IDESPECIALIDAD INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES (ID), 
)
GO 
CREATE TABLE MEDICOXHORARIO (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
IDMEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS(ID), 
IDHORARIO INT NOT NULL FOREIGN KEY REFERENCES HORARIOS (ID), 
)

--REGISTROS 
INSERT INTO ESPECIALIDADES VALUES ('Cirugía Pediátrica')
INSERT INTO ESPECIALIDADES VALUES ('Cirugía General')
INSERT INTO ESPECIALIDADES VALUES ('Dermatología')
INSERT INTO ESPECIALIDADES VALUES ('Gastroenterología')
INSERT INTO ESPECIALIDADES VALUES ('Hematología')
INSERT INTO ESPECIALIDADES VALUES ('Neurología ')
INSERT INTO ESPECIALIDADES VALUES ('Neumología')
INSERT INTO ESPECIALIDADES VALUES ('Oftalmología')
INSERT INTO ESPECIALIDADES VALUES ('Ortopedia')
INSERT INTO ESPECIALIDADES VALUES ('Otorrinolaringología')
INSERT INTO ESPECIALIDADES VALUES ('Pediatría')

--STORED PROCEDURE 
GO
CREATE PROCEDURE SP_AGREGARESTADO (
@Nombre varchar (60)
)
AS BEGIN
	INSERT INTO ESTADOS (ESTADO) VALUES(@nombre)
END

GO 

CREATE PROCEDURE SP_ActualizaEstado (
@Id int, 
@Nombre varchar (60)
) AS 
BEGIN 
	UPDATE ESTADOS SET ESTADO=@Nombre WHERE ID=@Id
END

GO 

CREATE PROCEDURE SP_AgregarHorario (
@Dia varchar (9),
@HoraInicio varchar (5),
@HoraFin varchar(5)
) AS
BEGIN 
	INSERT INTO HORARIOS VALUES (@Dia, @HoraInicio, @HoraFin)
END

GO 
CREATE PROCEDURE SP_ActualizarHorario (
@Id int,
@Dia varchar(9),
@HoraInicio varchar(5),
@HoraFin varchar(5)
) AS 
BEGIN 
	UPDATE HORARIOS SET DIA = @Dia, HORARIOINICIO = @HoraInicio, HORARIOFIN= @HoraFin where ID=@Id
END

GO 

CREATE PROCEDURE SP_AgregarEspecialidad (
@Especialidad varchar (60)
) AS 
BEGIN 
	INSERT INTO ESPECIALIDADES VALUES (@Especialidad)
END 

GO 
CREATE PROCEDURE SP_ActualizarEspecialidad (
@Id int, 
@Especialidad varchar (60)
) AS BEGIN 

	UPDATE ESPECIALIDADES SET ESPECIALIDAD = @Especialidad where ID = @Id
END

GO 

ALTER PROCEDURE SP_AgregarPersona (
@Nombre varchar (60),
@Apellido varchar (60),
@Dni varchar (60),
@Email varchar (60),
@Sexo varchar (1), 
@IdUsuario int null
) AS BEGIN 
	INSERT INTO USUARIOSDATOSPERSONALES(NOMBRE, APELLIDO, DNI, EMAIL, SEXO, IDUSUARIO) VALUES (@Nombre, @Apellido, @Dni, @Email, @Sexo, @IdUsuario)
END 

GO 

CREATE PROCEDURE SP_AgregarPaciente(
@FechaNacimiento date,
@Direccion varchar (60),
@Contacto varchar (60),
@IdPersona int
) AS BEGIN 
	INSERT INTO PACIENTES(FECHANACIMIENTO, DIRECCION, CONTACTO, ID_USUARIODATOPERSONAL) VALUES (@FechaNacimiento, @Direccion, @Contacto, @IdPersona)
END 

GO 

CREATE PROCEDURE SP_ActualizarPaciente (
@IdPaciente INT,
@FechaNacimiento date,
@Direccion varchar (60),
@Contacto varchar (60),
@IdPersona int,
@Nombre varchar (60),
@Apellido varchar (60),
@Dni varchar (60),
@Sexo varchar (1),
@Email varchar (60)
) AS BEGIN 
UPDATE USUARIOSDATOSPERSONALES SET NOMBRE = @Nombre, APELLIDO = @Apellido, DNI = @Dni, EMAIL=@Email, SEXO = @Sexo WHERE ID=@IdPersona;
UPDATE PACIENTES SET FECHANACIMIENTO = @FechaNacimiento, DIRECCION = @Direccion, CONTACTO = @Contacto WHERE ID = @IdPaciente;

END

GO 
CREATE PROCEDURE SP_AgregarUsuario (
@Usuario varchar(50), 
@Contrasenia varchar (50), 
@TipoUser int
)AS BEGIN 
INSERT INTO USUARIOS VALUES (@Usuario, @Contrasenia,@TipoUser)
END

GO 
CREATE PROCEDURE SP_AgregarMedico (
@IdPersona int
)AS BEGIN 
INSERT INTO MEDICOS VALUES (@IdPersona)
END
GO 
CREATE PROCEDURE SP_AgregarHorarioXMedico (
@IdMedico int,
@idHorario int
)AS BEGIN 

INSERT INTO MEDICOXHORARIO VALUES (@IdMedico, @idHorario)

END
GO

CREATE PROCEDURE SP_AgregarEspecialidadXMedico (
@IdMedico int,
@idEspecialidad int
)AS BEGIN 

INSERT INTO MEDICOXESPECIALIDAD VALUES (@IdMedico, @idEspecialidad)

END
GO
CREATE PROCEDURE SP_ActualizarPersona (
@IdPersona int,
@Nombre varchar(60),
@Apellido varchar(60),
@Dni varchar(60),
@Email varchar(60),
@Sexo varchar(1)
)as Begin 
	UPDATE USUARIOSDATOSPERSONALES SET NOMBRE = @Nombre, APELLIDO = @Apellido, DNI=@Dni, EMAIL= @Email, SEXO = @Sexo where ID = @IdPersona
End
Go
CREATE PROCEDURE SP_EliminarHorario (
@IdMedico int, 
@idHorario int
) AS BEGIN 

	DELETE FROM MEDICOXHORARIO WHERE IDMEDICO=@IdMedico AND IDHORARIO = @idHorario
END

GO 
CREATE PROCEDURE SP_EliminarEspecialidad (
@IdMedico INT,
@IdEspecialidad INT
) AS BEGIN 
 
 DELETE FROM MEDICOXESPECIALIDAD WHERE IDMEDICO= @IdMedico AND IDESPECIALIDAD=@IdEspecialidad

END


GO 

ALTER PROCEDURE SP_AgregarTurno (
@IdPaciente INT,
@IdMedico INT,
@IdEspecialidad INT,
@Fecha DATE,
@Horario VARCHAR(5),
@IdEstado INT, 
@Observacion varchar(500)
)AS BEGIN 
INSERT INTO TURNOS VALUES (@IdPaciente, @IdMedico,@IdEspecialidad, @Fecha, @Horario, @IdEstado, @Observacion)
END 

GO 

ALTER PROCEDURE SP_ActualizarTurno (
@Id INT,
@IdPaciente INT,
@IdMedico INT,
@IdEspecialidad INT,
@Fecha DATE,
@Horario VARCHAR(5),
@IdEstado INT,
@Observacion varchar(500)
)AS BEGIN 

UPDATE TURNOS SET IDPACIENTE = @IdPaciente, IDMEDICO = @IdMedico, IdEspecialidad = @IdEspecialidad, Fecha = @Fecha, Horario= @Horario, IdEstado = @IdEstado, OBSERVACION = @Observacion
where Id = @Id

END 

go
CREATE PROCEDURE SP_EliminaEstado (
@ID  INT
)AS BEGIN 

	DELETE ESTADOS WHERE ID = @ID
END 

GO
CREATE PROCEDURE SP_EliminaHorario(
@ID  INT
)AS BEGIN 

	DELETE HORARIOS WHERE ID = @ID
END 
go
CREATE PROCEDURE SP_EliminaEspecialidad(
@ID  INT
)AS BEGIN 

	DELETE ESPECIALIDADES WHERE ID = @ID
END 
GO 
CREATE PROCEDURE SP_EliminarPaciente(
@ID  INT
)AS BEGIN 

	DELETE PACIENTES WHERE ID = @ID
END 

GO
CREATE PROCEDURE SP_EliminarMedico(
@ID  INT
)AS BEGIN 

	DELETE MEDICOS WHERE ID = @ID
END 

GO 
CREATE PROCEDURE SP_EliminarTurno(
@ID  INT
)AS BEGIN 

	DELETE TURNOS WHERE ID = @ID
END 
GO 
alter PROCEDURE SP_ActualizarClaveUsuario (
@IdUsuario int, 
@Contrasenia varchar (50)
) AS BEGIN 
	UPDATE USUARIOS SET CONTRASENIA = @Contrasenia where Id = @IdUsuario
END

GO 
CREATE PROCEDURE SP_ActualizarUsuario (
@IdUsuario INT, 
@Usuario VARCHAR (50), 
@Clave VARCHAR (50)
)AS BEGIN 
	UPDATE USUARIOS SET USUARIO = @Usuario, CONTRASENIA = @Clave where ID = @IdUsuario

END

Go 
create procedure SP_EliminarPersona (
@Id int
)as begin 
	Delete USUARIOSDATOSPERSONALES WHERE ID = @Id
end

Go 
create procedure SP_EliminarUsuario (
@Id int
)as begin 
	Delete USUARIOS WHERE ID = @Id
end







