CREATE DATABASE AS_DB_CLINICA
go
USE AS_DB_CLINICA
GO

CREATE TABLE TIPOUSER(
	ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TIPO varchar(40) NOT NULL,
)
GO
CREATE TABLE USUARIOS(
ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY, 
USUARIO VARCHAR (50) NOT NULL, 
CONTRASENIA VARCHAR (50) NOT NULL,
IDTIPOUSER INT FOREIGN KEY REFERENCES TIPOUSER (ID) NOT NULL
)
GO 
CREATE TABLE ESTADOS (
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
ESTADO VARCHAR (60) NOT NULL
)
GO 
CREATE TABLE ESPECIALIDADES (
ID INT IDENTITY (1,1) NOT NULL PRIMARY KEY, 
ESPECIALIDAD VARCHAR (60) NOT NULL,
)
GO 
CREATE TABLE HORARIOS (
ID INT IDENTITY (1,1) PRIMARY KEY,
DIA VARCHAR (9) NOT NULL, 
HORARIOINICIO INT NOT NULL, 
HORARIOFIN INT NOT NULL
)
GO 
CREATE TABLE USUARIOSDATOSPERONALES (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
NOMBRE VARCHAR (60) NOT NULL, 
APELLIDO VARCHAR (60) NOT NULL, 
DNI VARCHAR (60) NULL, 
EMAIL VARCHAR (60) NULL,
SEXO VARCHAR (1) NOT NULL,
IDUSUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
)
GO 
CREATE TABLE MEDICOS (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
ID_USUARIODATOPERSONAL INT FOREIGN KEY REFERENCES USUARIOSDATOSPERONALES(ID)
)
GO 
CREATE TABLE PACIENTES (
ID INT PRIMARY KEY NOT NULL IDENTITY (1,1), 
FECHANACIMIENTO DATE NOT NULL, 
DIRECCION VARCHAR (60) NULL, 
CONTACTO VARCHAR (60) NULL,
ID_USUARIODATOPERSONAL INT FOREIGN KEY REFERENCES USUARIOSDATOSPERONALES(ID)
)
GO 
CREATE TABLE TURNOS (
ID INT PRIMARY KEY NOT NULL IDENTITY (1,1), 
IDPACIENTE INT NOT NULL FOREIGN KEY REFERENCES PACIENTES (ID), 
IDMEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS (ID), 
IDESPECIALIDAD INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES (ID), 
FECHA DATE NOT NULL, 
HORARIO VARCHAR (5) NOT NULL,
IDESTADO INT NOT NULL FOREIGN KEY REFERENCES ESTADOS (ID)
)
GO 
CREATE TABLE MEDICOXESPECIALIDAD (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
IDMEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS(ID), 
IDESPECIALIDAD INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES (ID), 
)
GO 
CREATE TABLE MEDICOXHORARIO (
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY, 
IDMEDICO INT NOT NULL FOREIGN KEY REFERENCES MEDICOS(ID), 
IDHORARIO INT NOT NULL FOREIGN KEY REFERENCES HORARIOS (ID), 
)

--REGISTROS 
INSERT INTO ESPECIALIDADES VALUES ('Cirugía Pediátrica')
INSERT INTO ESPECIALIDADES VALUES ('Cirugía General')
INSERT INTO ESPECIALIDADES VALUES ('Dermatología')
INSERT INTO ESPECIALIDADES VALUES ('Gastroenterología')
INSERT INTO ESPECIALIDADES VALUES ('Hematología')
INSERT INTO ESPECIALIDADES VALUES ('Neurología ')
INSERT INTO ESPECIALIDADES VALUES ('Neumología')
INSERT INTO ESPECIALIDADES VALUES ('Oftalmología')
INSERT INTO ESPECIALIDADES VALUES ('Ortopedia')
INSERT INTO ESPECIALIDADES VALUES ('Otorrinolaringología')
INSERT INTO ESPECIALIDADES VALUES ('Pediatría')

--STORED PROCEDURE 
GO
CREATE PROCEDURE SP_AGREGARESTADO (
@Nombre varchar (60)
)
AS BEGIN
	INSERT INTO ESTADOS (ESTADO) VALUES(@nombre)
END

GO 

CREATE PROCEDURE SP_ActualizaEstado (
@Id int, 
@Nombre varchar (60)
) AS 
BEGIN 
	UPDATE ESTADOS SET ESTADO=@Nombre WHERE ID=@Id
END

GO 

CREATE PROCEDURE SP_AgregarHorario (
@Dia varchar (9),
@HoraInicio varchar (5),
@HoraFin varchar(5)
) AS
BEGIN 
	INSERT INTO HORARIOS VALUES (@Dia, @HoraInicio, @HoraFin)
END

GO 
CREATE PROCEDURE SP_ActualizarHorario (
@Id int,
@Dia varchar(9),
@HoraInicio varchar(5),
@HoraFin varchar(5)
) AS 
BEGIN 
	UPDATE HORARIOS SET DIA = @Dia, HORARIOINICIO = @HoraInicio, HORARIOFIN= @HoraFin where ID=@Id
END

GO 

CREATE PROCEDURE SP_AgregarEspecialidad (
@Especialidad varchar (60)
) AS 
BEGIN 
	INSERT INTO ESPECIALIDADES VALUES (@Especialidad)
END 

GO 
CREATE PROCEDURE SP_ActualizarEspecialidad (
@Id int, 
@Especialidad varchar (60)
) AS BEGIN 

	UPDATE ESPECIALIDADES SET ESPECIALIDAD = @Especialidad where ID = @Id
END


